name: Lint Files

on:
  push:
    branches-ignore:
      - master

jobs:
  lint-client:
    name: Lint Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
      - name: Install Dependencies
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
